### ISSUE TITLE
Float error

### ISSUE THREAD

**Issue by caco3** [haverland/collectmeteranalog#5]
I now suddely got following error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/gruinelli/.local/lib/python3.10/site-packages/collectmeteranalog/__main__.py", line 47, in <module>
    main()
  File "/home/gruinelli/.local/lib/python3.10/site-packages/collectmeteranalog/__main__.py", line 42, in main
    collect(args.collect, args.days, keepolddata=args.keepdownloads, download=not args.nodownload, startlabel=args.startlabel, ticksteps=args.ticksteps)
  File "/home/gruinelli/.local/lib/python3.10/site-packages/collectmeteranalog/collect.py", line 206, in collect
    label(target_label_path, startlabel=startlabel, ticksteps=ticksteps)
  File "/home/gruinelli/.local/lib/python3.10/site-packages/collectmeteranalog/labeling.py", line 51, in label
    img, filelabel, filename, i = load_image(files, i, startlabel)
  File "/home/gruinelli/.local/lib/python3.10/site-packages/collectmeteranalog/labeling.py", line 253, in load_image
    category = float(target)
```

It can be fixed by replacing `category = float(target)` with
```
        try:
            category = float(target)
        except:
            category = 0
```

But I am not sure if this is the right approach, so I didn't create a PR

**Comment by haverland** [comment]
Fixed in code -> close
